intptr_t ptr;
intptr_t dma_ptr;

//This file was generated by RoSEBridge.scala, based on RoseAdapterParams
#define ROSE_PORT_COUNT 2
#define ROSE_PORT_WIDTH 32
#define ROSE_STATUS_ADDR (ptr)

#define ROSE_TX_DATA_ADDR (ptr + 0x08)
#define ROSE_TX_ENQ_READY (reg_read32(ROSE_STATUS_ADDR) & 0x1)

//DMA_DMA0_port_channel_0
#define ROSE_DMA_CONFIG_COUNTER_ADDR_0 (ptr + 0x10)
#define ROSE_DMA_CURR_COUNTER_ADDR_0 (ptr + 0x14)
#define ROSE_DMA_BASE_ADDR_0 (dma_ptr + 0x00)
#define ROSE_DMA_BUFFER_0 (reg_read32(ROSE_STATUS_ADDR) & 0x4)
#define ROSE_DMA_CURR_COUNTER_0 (reg_read32(ROSE_DMA_CURR_COUNTER_ADDR_0))

//reqrsp_reqrsp0_port_channel_1
#define ROSE_RX_DATA_ADDR_1 (ptr + 0x0c)
#define ROSE_RX_DATA_1 (reg_read32(ROSE_RX_DATA_ADDR_1))
#define ROSE_RX_DEQ_VALID_1 (reg_read32(ROSE_STATUS_ADDR) & 0x2)